### ISSUE TITLE
CloudTrail Event Filtering:

### ISSUE THREAD

**Issue by EreminAnton** [fivexl/terraform-aws-cloudtrail-to-slack#38]
Chat GPT:
Rather than filtering events within your Python code, you could make use of AWS CloudTrail’s built-in event filtering capabilities. This could reduce the number of events that your lambda function needs to process, and might reduce costs and increase performance.

See if it is possible and makes sense.

**Comment by Andrey9kin** [comment]
We want to keep recording all events
